// <auto-generated />
namespace AssignmentTest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class catename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(catename));
        
        string IMigrationMetadata.Id
        {
            get { return "202203180216346_catename"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
